package EmpiricalTestForRandomNumberGenerators;

import RandomNumberGenerators.UnifRandGenerator;

import java.util.ArrayList;

/**
 * More direct test of the independence assumption and only this. It does not test for uniformity
 */
public class RunsUpTest {
    /**
     * This tests for the amount of uniformly increasing subsequences in the sequence generated by the random number generator
     * @param r
     * @param n
     */
    public static void runsUpTest(UnifRandGenerator r, int n) {
        //1. generate n random u
        ArrayList<Double> u = new ArrayList<>();
        for(int i = 0; i < n; i++) {
            u.add(r.getRandomNumber());
        }
        //2. create the counters for runs up
        //ArrayList
    }
}
